encode : vigenere.py
	python3 vigenere.py -e $(ARGS)

decode : vigenere.py
	python3 vigenere.py -d $(ARGS)

guesskeylength : vigenere.py
	python3 vigenere.py -g $(ARGS)

crack : vigenere.py
	python3 vigenere.py -c $(ARGS)