#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ServoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Project Title: Test Bed
  Team Members: Deven Maheshwari, Francisco Aum, Michelle Zhang, Faith Wilson
  Date: 11/18/21
  Section: 6


  Task Description:
  Controlling one motor


  Pseudocode:
  Turn rightMotor on forward at halfspeed for 5 seconds then stop
  Turn leftMotor on forward at 3/4 fspeed for 2.5 seconds then stop
  Turn both motors on at full power, same direction, 7.25 seconds then stop
*/

task main()
{                                     //Program begins, insert code within curly braces

// Task 1
startMotor(port2, 64);
wait(5);
stopMotor(port2);

// Task 2
startMotor(port3, 96);
wait(2.5);
stopMotor(port3);

// Task 3
startMotor(port3, 127);
startMotor(port2, 127);
wait(7.25);
stopMotor();


}
