#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ServoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Project Title: Test Bed
  Team Members: Deven Maheshwari, Francisco Aum, Michelle Zhang, Faith Wilson
  Date: 11/22/21
  Section: 6


  Task Description:
  Controlling a servo motor


*/

task main()
{                                     //Program begins, insert code within curly braces

// Sample
setServo(ServoMotor, -127);
wait(2);
setServo(ServoMotor, 0);
wait(2);
setServo(ServoMotor, 127);
wait(2);


// a
setServo(ServoMotor, -127);
wait(2);
// b
setServo(ServoMotor, -63);
wait(3);
// c
setServo(ServoMotor, 0);
wait(2);
// d
setServo(ServoMotor, 63);
wait(2);
// e
setServo(ServoMotor, 127);
wait(2);


}
