#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ServoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Test Bed
  Team Members: Deven Maheshwari, Francisco Aum, Michelle Zhang, Faith Wilson
  Date: 11/17/21
  Section: 6


  Task Description:
	Turn VEX LED on and off.

  Pseudocode:
  On
  Wait
  Off

*/

task main()
{                                     //Program begins, insert code within curly braces

turnLEDOff(green);
wait(1);
turnLEDOn(green);
wait(1);
turnLEDOff(green);
wait(1);
turnLEDOn(green);
wait(1);
turnLEDOff(green);


}
