#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ServoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Test Bed
  Team Members: Deven Maheshwari, Francisco Aum, Michelle Zhang, Faith Wilson
  Date: 11/17/21
  Section: 6


  Task Description:
  Controlling one motor


  Pseudocode:
  Turn rightMotor on forward at halfspeed for 5 seconds
  Stop motor

*/

task main()
{                                     //Program begins, insert code within curly braces

startMotor(port2, 64);

// (15) Starts left motor same time as right motor
startMotor(port3, 64);

wait(5);
stopMotor();

// (17) Reverse motors 2 different ways

// Method 1
startMotor(port2, -64);
startMotor(port3, -64);
wait(5);
stopMotor();

//Method 2
backward(64);
wait(5);




}
