#pragma config(Sensor, in1,    linefollower1,  sensorLineFollower)
#pragma config(Sensor, in2,    linefollower2,  sensorLineFollower)
#pragma config(Sensor, in3,    linefollower3,  sensorLineFollower)
#pragma config(Sensor, dgtl12, jumper,         sensorLEDtoVCC)
#pragma config(Motor,  port2,           rt,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rb,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lt,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lb,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           conveyer,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           conveyer2,      tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*    Deven Maheshwari, Francisco Aum, Faith Wilson, Michelle Zhang          */
/*        r = right, l = left, t = top, b = bottom                           */
/*                           January, 2022                                   */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void tright()
	{
		startMotor(lt, 30);
		startMotor(lb, 30);
		startMotor(rt, -30);
		startMotor(rb, -30);
		wait(1);
		stopMotor(lt);
		stopMotor(rt);
		stopMotor(rb);
		stopMotor(lb);
	}

void tleft()
	{
		startMotor(lt, -30);
		startMotor(lb, -30);
		startMotor(rt, 30);
		startMotor(rb, 30);
		wait(1);
		stopMotor(lt);
		stopMotor(rt);
		stopMotor(rb);
		stopMotor(lb);
	}

task autonomous()
{
/*
	int threshold = 505;


  clearTimer(T1);

	while(time1[T1] < 30000)
  {

    // sensor sees light:
    if(SensorValue(linefollower2) < threshold)
    {
      motor[lt]  = 32;
      motor[rt] = 32;
      motor[lb]  = 32;
      motor[rb] = 32;
    }
  }
*/
		startMotor(rt, 127);
		startMotor(lt, 127);
		startMotor(rb, 127);
		startMotor(lb, 127);
		wait(3);
		if (SensorValue(jumper) == 1)
		{
			tright();
			wait(1.5);
			startMotor(rt, 127);
			startMotor(lt, 127);
			startMotor(rb, 127);
			startMotor(lb, 127);
			wait(2);
			stopMotor(rt);
			stopMotor(lt);
			stopMotor(rb);
			stopMotor(lb);
		}
		else
		{
			tleft();
			wait(1.5);
			startMotor(rt, 127);
			startMotor(lt, 127);
			startMotor(rb, 127);
			startMotor(lb, 127);
			wait(2);
			stopMotor(rt);
			stopMotor(lt);
			stopMotor(rb);
			stopMotor(lb);
		}
		startMotor(conveyer, -127);
		wait(1);
		stopMotor(conveyer);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	while(1 == 1)
	{
    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[rt] = vexRT[Ch2];
    motor[rb]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[lt] = vexRT[Ch3];
    motor[lb]  = vexRT[Ch3];

    // Conveyer
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[conveyer] = 127;
			motor[conveyer2] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[conveyer] = -127;
			motor[conveyer2] = -127;
		}
		else
		{
			motor[conveyer] = 0;
			motor[conveyer] = 0;
		}


	}
}
